### ISSUE TITLE
question about MCCA

### ISSUE THREAD

**Issue by alienx-zero** [jameschapman19/cca_zoo#158]
I want to use SCCA in MCCA, not rCCA, so I make modification as follow: 
\# class MCCA(rCCA):
class MCCA(SCCA_PMD):

**but the error arise:**
D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Traceback (most recent call last):

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "h:\phd\learning\research\modality_fusion\multicca_main.py", line 16, in <module>
    from cca_zoo.models import MCCA

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\__init__.py", line 3, in <module>
    from .models import *

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\__init__.py", line 1, in <module>
    from ._grcca import GRCCA

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_grcca.py", line 6, in <module>
    from cca_zoo.models._multiview._mcca import MCCA

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_multiview\__init__.py", line 2, in <module>
    from ._mcca import MCCA, KCCA

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_multiview\_mcca.py", line 9, in <module>
    from cca_zoo.models._iterative import SCCA_PMD

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_iterative\__init__.py", line 1, in <module>
    from ._altmaxvar import AltMaxVar

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_iterative\_altmaxvar.py", line 6, in <module>
    from ._base import _BaseInnerLoop

  File "D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_iterative\_base.py", line 12, in <module>
    from .._multiview._mcca import MCCA, KCCA

ImportError: cannot import name 'MCCA' from partially initialized module 'cca_zoo.models._multiview._mcca' (most likely due to a circular import) (D:\Users\99488\anaconda3\envs\torch_gnn\lib\site-packages\cca_zoo\models\_multiview\_mcca.py)

**Comment by jameschapman19** [comment]
If I understand correctly you should just be able to use SCCA_PMD out the box with multiple views by

SCCA_PMD().fit((x,y,z))

So don't need to worry about the inheritance.

**Comment by jameschapman19** [comment]
If you are trying to build a new method on top of SCCA_PMD then I think you'll be ok if it's got a different name to the models in the cca_zoo namespace eg MCCA_EDIT(SCCA_PMD) I think these circular imports are often caused by these kinds of conflict.

**Comment by alienx-zero** [comment]
Great, thanks for let me know~ Maybe you can mention this in the document since for R, the CCA and MultiCCA was splited in two functions
