### ISSUE TITLE
AttributeError: 'GCCA' object has no attribute 'tol'

### ISSUE THREAD

**Issue by Peter-Devine** [jameschapman19/cca_zoo#8]
First off, thanks for the package!

When I run the below code:

```
from cca_zoo import wrappers
import numpy as np

linear_cca = wrappers.GCCA(latent_dims=22, tol=1e-05)

# create data in advance
a = np.random.rand(50, 50)
b = np.random.rand(50, 60)
x = np.random.rand(50, 90)

linear_cca.fit(a,b,x)
```

it returns the following error at the last line:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\TEMP\python_envs\notebook_env\lib\site-packages\sklearn\base.py", line 260, in __repr__
    repr_ = pp.pformat(self)
  File "C:\TEMP\python_envs\notebook_env\lib\pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "C:\TEMP\python_envs\notebook_env\lib\pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "C:\TEMP\python_envs\notebook_env\lib\pprint.py", line 393, in _repr
    self._depth, level)
  File "C:\TEMP\python_envs\notebook_env\lib\site-packages\sklearn\utils\_pprint.py", line 181, in format
    changed_only=self._changed_only)
  File "C:\TEMP\python_envs\notebook_env\lib\site-packages\sklearn\utils\_pprint.py", line 425, in _safe_repr
    params = _changed_params(object)
  File "C:\TEMP\python_envs\notebook_env\lib\site-packages\sklearn\utils\_pprint.py", line 91, in _changed_params
    params = estimator.get_params(deep=False)
  File "C:\TEMP\python_envs\notebook_env\lib\site-packages\sklearn\base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'GCCA' object has no attribute 'tol'
```

Can you reproduce this error?

Thanks again

**Comment by jameschapman19** [comment]
My mistake - updated the parameters of gcca without updating tutorial notebook. If you remove tol it should work and I'll update the tutorial ASAP.

Best,

James
________________________________

**Comment by jameschapman19** [comment]
I'll also ensure this doesn't happen again by adding a test to check the tutorial runs

**Comment by jameschapman19** [comment]
Update: I checked this and realised the reason I wasn't picking up the error was because I wasn't testing with the new version of scikit learn. If you install my latest version of this package (1.1.12) it should work (although you'd need to add regularisation in this case as dimensionality is bigger than the number of rows)

**Comment by jameschapman19** [comment]
thanks for picking up!
